gsap.from(".nameBox", {x: '-100%', duration: 1.5, ease: 'power2'})
gsap.from("#aboutMe", {opacity: 0, y: '-100%', delay: 1, duration: 1, ease: 'power2'})
gsap.from("#projectsBox", {opacity: 0, x: '-100vw', delay: 1.5, duration: 1.5, ease: 'power2'})
gsap.from(".nbBtn", {opacity: 0, x: '-100vw', rotation: 360, stagger: .5, duration: 1})
gsap.from("h1", { opacity: 0, duration: .5, delay: 1.5})
gsap.from("h3", { opacity: 0, rotation: 180, duration: .5, delay: 1.8})
gsap.from("h4", { opacity: 0, rotation: 180, duration: .5, delay: 1.8})
gsap.from("#aboutPara", {x: '-20%', opacity: 0, delay: 2.5, duration: .5})
gsap.from("#waveTop", { opacity: 0, y: '-100%', delay: .5, duration: 1.3})